stages:
  prepare_data:
    cmd: python cli_rag.py --embed
    deps:
      - input-datasets/recipe_cookbook.feather
    outs:
      - outputs/recipe_small.jsonl
  
  load_data:
    cmd: python cli_rag.py --load
    deps:
      - outputs/recipe_small.jsonl
    outs:
      - ${CHROMADB_DATA_DIR}:
          cache: false
          persist: true

  query_model:
    cmd: python cli_rag.py --query
    deps:
      - ${CHROMADB_DATA_DIR}

metrics:
  - query_metrics.json