name: discovery-generative-ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.17
  - pip
  - pip:
      - google-generativeai
      - vertexai
      - langchain
      - chromadb
      - python-dotenv
      - streamlit-option-menu
      - onnxruntime==1.17.0
      - requests==2.28.1
      - openai==0.28.0
      - streamlit==1.24.1
      - poetry==1.5.1
  - gcc
  - cmake
