name: Set Up Poetry Environment
description: Install Python and Poetry. Credits to Andre Sionek for writing the original GitHub Action.

inputs:
  python_version:
    description: Python version
    required: true
    default: '3.9.17'
    type: string

  poetry_version:
    description: Poetry version
    required: true
    default: '1.2.2'
    type: string

runs:
  using: "composite"
  steps:

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}

    - name: Cache Poetry dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pypoetry
          ~/.local
        key: ${{ runner.os }}-poetry-${{ inputs.poetry_version }}-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-poetry-${{ inputs.poetry_version }}-

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        version: ${{ inputs.poetry_version }}

    - name: Install Python Dependencies with Poetry
      shell: bash
      run: poetry install
