networks:
    default:
        name: recipe-rag-network
        external: true
services:
    recipe-rag-cli:
        image: recipe-rag-cli
        container_name: recipe-rag-cli
        volumes:
            - ../secrets:/secrets
            - ../datapipeline:/app
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
            GCP_PROJECT: $GCP_PROJECT
            GCS_BUCKET_NAME: $GCS_BUCKET_NAME
        depends_on:
            - chromadb

    chromadb:
        image: chromadb/chroma:latest
        container_name: recipe-rag-chromadb
        ports:
            - 8000:8000
        volumes:
            - ./docker-volumes/chromadb:/chroma/chroma
        environment:
            - IS_PERSISTENT=TRUE
            - ANONYMIZED_TELEMETRY=FALSE
            - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"] # This is not recommended for production environments.

