name: CI/CD Pipeline
run-name: ${{ github.actor }} submitted a CI CD Action

on:
  push:
    branches: 
      - 'hanna/ci'
  pull_request:
    branches: 
      - 'hanna/ci'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - id: 'auth'
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
    
    - name: Configure Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    
    - name: Create Docker Network
      run: docker network create recipe-rag-network || true
      
    - name: Setup Directories
      run: |
        mkdir -p src/secrets
        echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > src/secrets/llm-service-account-cassie.json
      
    - name: Run Tests
      run: |
        cd tests/integration
        # Run tests and send output directly to GitHub Actions log
        docker-compose build --no-cache
        docker-compose up --abort-on-container-exit --exit-code-from recipe-rag-cli 2>&1 | tee test_output.log
        # Check if tests passed
        if [ ${PIPESTATUS[0]} -eq 0 ]; then
          echo "Tests passed successfully!"
        else
          echo "Tests failed!"
          exit 1
        fi
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}

    - name: Clean up
      if: always()
      run: |
        cd tests/integration
        docker-compose down -v
        docker network rm recipe-rag-network || true