name: CI/CD Pipeline
run-name: ${{ github.actor }} submitted a CI CD Action

on:
  push:
    branches: 
      - 'hanna/ci'
  pull_request:
    branches: 
      - 'hanna/ci'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    # Install all Python versions needed
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Match datapipeline Dockerfile
    
    - id: 'auth'
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
    
    - name: Configure Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    
    - name: Create Docker Network
      run: docker network create recipe-rag-network || true
      
    # Add permission fix step
    - name: Fix Permissions
      run: |
        sudo chown -R 1000:1000 .
        mkdir -p src/datapipeline/docker-volumes/chromadb
        sudo chmod -R 777 src/datapipeline/docker-volumes
        
    - name: Run Tests
      run: |
        cd tests/integration
        docker-compose build --no-cache  # Force rebuild to ensure clean state
        docker-compose up --abort-on-container-exit --exit-code-from recipe-rag-cli
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
        
    # Add debug logs step
    - name: Print Docker logs on failure
      if: failure()
      run: |
        cd tests/integration
        docker-compose logs
        
    - name: Upload Coverage Reports
      uses: codecov/codecov-action@v3
      with:
        files: ./src/datapipeline/coverage.xml,./src/food-detection/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

    - name: Clean up
      if: always()
      run: |
        cd tests/integration
        docker-compose down -v
        docker network rm recipe-rag-network || true