name: ML Pipeline CI/CD

on:
  push:
    branches: [hanna_mlworkflow]
  pull_request:
    branches: [hanna_mlworkflow]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true

    - name: Build and Run Docker Pipeline
      run: |
        cd src/ml-pipeline
        chmod +x docker-shell.sh
        ./docker-shell.sh python cli.py --pipeline